// Generated by gencpp from file app_loader/AppLoad.msg
// DO NOT EDIT!


#ifndef APP_LOADER_MESSAGE_APPLOAD_H
#define APP_LOADER_MESSAGE_APPLOAD_H

#include <ros/service_traits.h>


#include <app_loader/AppLoadRequest.h>
#include <app_loader/AppLoadResponse.h>


namespace app_loader
{

struct AppLoad
{

typedef AppLoadRequest Request;
typedef AppLoadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AppLoad
} // namespace app_loader


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::app_loader::AppLoad > {
  static const char* value()
  {
    return "9e491318c68b9fbf00509a80adfec2ec";
  }

  static const char* value(const ::app_loader::AppLoad&) { return value(); }
};

template<>
struct DataType< ::app_loader::AppLoad > {
  static const char* value()
  {
    return "app_loader/AppLoad";
  }

  static const char* value(const ::app_loader::AppLoad&) { return value(); }
};


// service_traits::MD5Sum< ::app_loader::AppLoadRequest> should match 
// service_traits::MD5Sum< ::app_loader::AppLoad > 
template<>
struct MD5Sum< ::app_loader::AppLoadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::app_loader::AppLoad >::value();
  }
  static const char* value(const ::app_loader::AppLoadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::app_loader::AppLoadRequest> should match 
// service_traits::DataType< ::app_loader::AppLoad > 
template<>
struct DataType< ::app_loader::AppLoadRequest>
{
  static const char* value()
  {
    return DataType< ::app_loader::AppLoad >::value();
  }
  static const char* value(const ::app_loader::AppLoadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::app_loader::AppLoadResponse> should match 
// service_traits::MD5Sum< ::app_loader::AppLoad > 
template<>
struct MD5Sum< ::app_loader::AppLoadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::app_loader::AppLoad >::value();
  }
  static const char* value(const ::app_loader::AppLoadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::app_loader::AppLoadResponse> should match 
// service_traits::DataType< ::app_loader::AppLoad > 
template<>
struct DataType< ::app_loader::AppLoadResponse>
{
  static const char* value()
  {
    return DataType< ::app_loader::AppLoad >::value();
  }
  static const char* value(const ::app_loader::AppLoadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // APP_LOADER_MESSAGE_APPLOAD_H
