// Generated by gencpp from file app_loader/AppUnload.msg
// DO NOT EDIT!


#ifndef APP_LOADER_MESSAGE_APPUNLOAD_H
#define APP_LOADER_MESSAGE_APPUNLOAD_H

#include <ros/service_traits.h>


#include <app_loader/AppUnloadRequest.h>
#include <app_loader/AppUnloadResponse.h>


namespace app_loader
{

struct AppUnload
{

typedef AppUnloadRequest Request;
typedef AppUnloadResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AppUnload
} // namespace app_loader


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::app_loader::AppUnload > {
  static const char* value()
  {
    return "9e491318c68b9fbf00509a80adfec2ec";
  }

  static const char* value(const ::app_loader::AppUnload&) { return value(); }
};

template<>
struct DataType< ::app_loader::AppUnload > {
  static const char* value()
  {
    return "app_loader/AppUnload";
  }

  static const char* value(const ::app_loader::AppUnload&) { return value(); }
};


// service_traits::MD5Sum< ::app_loader::AppUnloadRequest> should match 
// service_traits::MD5Sum< ::app_loader::AppUnload > 
template<>
struct MD5Sum< ::app_loader::AppUnloadRequest>
{
  static const char* value()
  {
    return MD5Sum< ::app_loader::AppUnload >::value();
  }
  static const char* value(const ::app_loader::AppUnloadRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::app_loader::AppUnloadRequest> should match 
// service_traits::DataType< ::app_loader::AppUnload > 
template<>
struct DataType< ::app_loader::AppUnloadRequest>
{
  static const char* value()
  {
    return DataType< ::app_loader::AppUnload >::value();
  }
  static const char* value(const ::app_loader::AppUnloadRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::app_loader::AppUnloadResponse> should match 
// service_traits::MD5Sum< ::app_loader::AppUnload > 
template<>
struct MD5Sum< ::app_loader::AppUnloadResponse>
{
  static const char* value()
  {
    return MD5Sum< ::app_loader::AppUnload >::value();
  }
  static const char* value(const ::app_loader::AppUnloadResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::app_loader::AppUnloadResponse> should match 
// service_traits::DataType< ::app_loader::AppUnload > 
template<>
struct DataType< ::app_loader::AppUnloadResponse>
{
  static const char* value()
  {
    return DataType< ::app_loader::AppUnload >::value();
  }
  static const char* value(const ::app_loader::AppUnloadResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // APP_LOADER_MESSAGE_APPUNLOAD_H
