// Generated by gencpp from file app_loader/RTDestroy.msg
// DO NOT EDIT!


#ifndef APP_LOADER_MESSAGE_RTDESTROY_H
#define APP_LOADER_MESSAGE_RTDESTROY_H

#include <ros/service_traits.h>


#include <app_loader/RTDestroyRequest.h>
#include <app_loader/RTDestroyResponse.h>


namespace app_loader
{

struct RTDestroy
{

typedef RTDestroyRequest Request;
typedef RTDestroyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RTDestroy
} // namespace app_loader


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::app_loader::RTDestroy > {
  static const char* value()
  {
    return "36405beac40f6723e71d2520ae768ec2";
  }

  static const char* value(const ::app_loader::RTDestroy&) { return value(); }
};

template<>
struct DataType< ::app_loader::RTDestroy > {
  static const char* value()
  {
    return "app_loader/RTDestroy";
  }

  static const char* value(const ::app_loader::RTDestroy&) { return value(); }
};


// service_traits::MD5Sum< ::app_loader::RTDestroyRequest> should match 
// service_traits::MD5Sum< ::app_loader::RTDestroy > 
template<>
struct MD5Sum< ::app_loader::RTDestroyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::app_loader::RTDestroy >::value();
  }
  static const char* value(const ::app_loader::RTDestroyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::app_loader::RTDestroyRequest> should match 
// service_traits::DataType< ::app_loader::RTDestroy > 
template<>
struct DataType< ::app_loader::RTDestroyRequest>
{
  static const char* value()
  {
    return DataType< ::app_loader::RTDestroy >::value();
  }
  static const char* value(const ::app_loader::RTDestroyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::app_loader::RTDestroyResponse> should match 
// service_traits::MD5Sum< ::app_loader::RTDestroy > 
template<>
struct MD5Sum< ::app_loader::RTDestroyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::app_loader::RTDestroy >::value();
  }
  static const char* value(const ::app_loader::RTDestroyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::app_loader::RTDestroyResponse> should match 
// service_traits::DataType< ::app_loader::RTDestroy > 
template<>
struct DataType< ::app_loader::RTDestroyResponse>
{
  static const char* value()
  {
    return DataType< ::app_loader::RTDestroy >::value();
  }
  static const char* value(const ::app_loader::RTDestroyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // APP_LOADER_MESSAGE_RTDESTROY_H
