# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from gsdf_msgs/CommHeader.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class CommHeader(genpy.Message):
  _md5sum = "9d7273660b11e3521033af5d52ed4460"
  _type = "gsdf_msgs/CommHeader"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int16 source
int8 type
int16 data_len
int8 version
int16 checksum
"""
  __slots__ = ['source','type','data_len','version','checksum']
  _slot_types = ['int16','int8','int16','int8','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       source,type,data_len,version,checksum

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CommHeader, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.source is None:
        self.source = 0
      if self.type is None:
        self.type = 0
      if self.data_len is None:
        self.data_len = 0
      if self.version is None:
        self.version = 0
      if self.checksum is None:
        self.checksum = 0
    else:
      self.source = 0
      self.type = 0
      self.data_len = 0
      self.version = 0
      self.checksum = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_hbhbh().pack(_x.source, _x.type, _x.data_len, _x.version, _x.checksum))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.source, _x.type, _x.data_len, _x.version, _x.checksum,) = _get_struct_hbhbh().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_hbhbh().pack(_x.source, _x.type, _x.data_len, _x.version, _x.checksum))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.source, _x.type, _x.data_len, _x.version, _x.checksum,) = _get_struct_hbhbh().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_hbhbh = None
def _get_struct_hbhbh():
    global _struct_hbhbh
    if _struct_hbhbh is None:
        _struct_hbhbh = struct.Struct("<hbhbh")
    return _struct_hbhbh
