// Generated by gencpp from file gsdf_msgs/BarrierAck.msg
// DO NOT EDIT!


#ifndef GSDF_MSGS_MESSAGE_BARRIERACK_H
#define GSDF_MSGS_MESSAGE_BARRIERACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gsdf_msgs
{
template <class ContainerAllocator>
struct BarrierAck_
{
  typedef BarrierAck_<ContainerAllocator> Type;

  BarrierAck_()
    : robot_id(0)  {
    }
  BarrierAck_(const ContainerAllocator& _alloc)
    : robot_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _robot_id_type;
  _robot_id_type robot_id;





  typedef boost::shared_ptr< ::gsdf_msgs::BarrierAck_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gsdf_msgs::BarrierAck_<ContainerAllocator> const> ConstPtr;

}; // struct BarrierAck_

typedef ::gsdf_msgs::BarrierAck_<std::allocator<void> > BarrierAck;

typedef boost::shared_ptr< ::gsdf_msgs::BarrierAck > BarrierAckPtr;
typedef boost::shared_ptr< ::gsdf_msgs::BarrierAck const> BarrierAckConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gsdf_msgs::BarrierAck_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gsdf_msgs::BarrierAck_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gsdf_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'gsdf_msgs': ['/home/plankton/DDP/src/micros_swarm_framework/core/gsdf_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gsdf_msgs::BarrierAck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gsdf_msgs::BarrierAck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gsdf_msgs::BarrierAck_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gsdf_msgs::BarrierAck_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gsdf_msgs::BarrierAck_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gsdf_msgs::BarrierAck_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gsdf_msgs::BarrierAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "91b3babccc3ad4274601f80c372a0375";
  }

  static const char* value(const ::gsdf_msgs::BarrierAck_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x91b3babccc3ad427ULL;
  static const uint64_t static_value2 = 0x4601f80c372a0375ULL;
};

template<class ContainerAllocator>
struct DataType< ::gsdf_msgs::BarrierAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gsdf_msgs/BarrierAck";
  }

  static const char* value(const ::gsdf_msgs::BarrierAck_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gsdf_msgs::BarrierAck_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 robot_id\n\
";
  }

  static const char* value(const ::gsdf_msgs::BarrierAck_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gsdf_msgs::BarrierAck_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BarrierAck_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gsdf_msgs::BarrierAck_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gsdf_msgs::BarrierAck_<ContainerAllocator>& v)
  {
    s << indent << "robot_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GSDF_MSGS_MESSAGE_BARRIERACK_H
