// Generated by gencpp from file gsdf_msgs/BlackBoardPut.msg
// DO NOT EDIT!


#ifndef GSDF_MSGS_MESSAGE_BLACKBOARDPUT_H
#define GSDF_MSGS_MESSAGE_BLACKBOARDPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gsdf_msgs
{
template <class ContainerAllocator>
struct BlackBoardPut_
{
  typedef BlackBoardPut_<ContainerAllocator> Type;

  BlackBoardPut_()
    : bb_id(0)
    , on_robot_id(0)
    , key()
    , value()
    , timestamp()
    , robot_id(0)  {
    }
  BlackBoardPut_(const ContainerAllocator& _alloc)
    : bb_id(0)
    , on_robot_id(0)
    , key(_alloc)
    , value(_alloc)
    , timestamp()
    , robot_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _bb_id_type;
  _bb_id_type bb_id;

   typedef int32_t _on_robot_id_type;
  _on_robot_id_type on_robot_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _key_type;
  _key_type key;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _value_type;
  _value_type value;

   typedef ros::Time _timestamp_type;
  _timestamp_type timestamp;

   typedef int32_t _robot_id_type;
  _robot_id_type robot_id;





  typedef boost::shared_ptr< ::gsdf_msgs::BlackBoardPut_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gsdf_msgs::BlackBoardPut_<ContainerAllocator> const> ConstPtr;

}; // struct BlackBoardPut_

typedef ::gsdf_msgs::BlackBoardPut_<std::allocator<void> > BlackBoardPut;

typedef boost::shared_ptr< ::gsdf_msgs::BlackBoardPut > BlackBoardPutPtr;
typedef boost::shared_ptr< ::gsdf_msgs::BlackBoardPut const> BlackBoardPutConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gsdf_msgs::BlackBoardPut_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gsdf_msgs::BlackBoardPut_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gsdf_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'gsdf_msgs': ['/home/plankton/DDP/src/micros_swarm_framework/core/gsdf_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gsdf_msgs::BlackBoardPut_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gsdf_msgs::BlackBoardPut_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gsdf_msgs::BlackBoardPut_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gsdf_msgs::BlackBoardPut_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gsdf_msgs::BlackBoardPut_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gsdf_msgs::BlackBoardPut_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gsdf_msgs::BlackBoardPut_<ContainerAllocator> >
{
  static const char* value()
  {
    return "21fe3110556151fb76fd0bddb9325f46";
  }

  static const char* value(const ::gsdf_msgs::BlackBoardPut_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x21fe3110556151fbULL;
  static const uint64_t static_value2 = 0x76fd0bddb9325f46ULL;
};

template<class ContainerAllocator>
struct DataType< ::gsdf_msgs::BlackBoardPut_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gsdf_msgs/BlackBoardPut";
  }

  static const char* value(const ::gsdf_msgs::BlackBoardPut_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gsdf_msgs::BlackBoardPut_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 bb_id\n\
int32 on_robot_id\n\
string key\n\
uint8[] value\n\
time timestamp\n\
int32 robot_id\n\
";
  }

  static const char* value(const ::gsdf_msgs::BlackBoardPut_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gsdf_msgs::BlackBoardPut_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bb_id);
      stream.next(m.on_robot_id);
      stream.next(m.key);
      stream.next(m.value);
      stream.next(m.timestamp);
      stream.next(m.robot_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BlackBoardPut_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gsdf_msgs::BlackBoardPut_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gsdf_msgs::BlackBoardPut_<ContainerAllocator>& v)
  {
    s << indent << "bb_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.bb_id);
    s << indent << "on_robot_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.on_robot_id);
    s << indent << "key: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.key);
    s << indent << "value[]" << std::endl;
    for (size_t i = 0; i < v.value.size(); ++i)
    {
      s << indent << "  value[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.value[i]);
    }
    s << indent << "timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.timestamp);
    s << indent << "robot_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GSDF_MSGS_MESSAGE_BLACKBOARDPUT_H
