// Generated by gencpp from file gsdf_msgs/CommHeader.msg
// DO NOT EDIT!


#ifndef GSDF_MSGS_MESSAGE_COMMHEADER_H
#define GSDF_MSGS_MESSAGE_COMMHEADER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gsdf_msgs
{
template <class ContainerAllocator>
struct CommHeader_
{
  typedef CommHeader_<ContainerAllocator> Type;

  CommHeader_()
    : source(0)
    , type(0)
    , data_len(0)
    , version(0)
    , checksum(0)  {
    }
  CommHeader_(const ContainerAllocator& _alloc)
    : source(0)
    , type(0)
    , data_len(0)
    , version(0)
    , checksum(0)  {
  (void)_alloc;
    }



   typedef int16_t _source_type;
  _source_type source;

   typedef int8_t _type_type;
  _type_type type;

   typedef int16_t _data_len_type;
  _data_len_type data_len;

   typedef int8_t _version_type;
  _version_type version;

   typedef int16_t _checksum_type;
  _checksum_type checksum;





  typedef boost::shared_ptr< ::gsdf_msgs::CommHeader_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gsdf_msgs::CommHeader_<ContainerAllocator> const> ConstPtr;

}; // struct CommHeader_

typedef ::gsdf_msgs::CommHeader_<std::allocator<void> > CommHeader;

typedef boost::shared_ptr< ::gsdf_msgs::CommHeader > CommHeaderPtr;
typedef boost::shared_ptr< ::gsdf_msgs::CommHeader const> CommHeaderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gsdf_msgs::CommHeader_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gsdf_msgs::CommHeader_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gsdf_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'gsdf_msgs': ['/home/plankton/DDP/src/micros_swarm_framework/core/gsdf_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gsdf_msgs::CommHeader_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gsdf_msgs::CommHeader_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gsdf_msgs::CommHeader_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gsdf_msgs::CommHeader_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gsdf_msgs::CommHeader_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gsdf_msgs::CommHeader_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gsdf_msgs::CommHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d7273660b11e3521033af5d52ed4460";
  }

  static const char* value(const ::gsdf_msgs::CommHeader_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d7273660b11e352ULL;
  static const uint64_t static_value2 = 0x1033af5d52ed4460ULL;
};

template<class ContainerAllocator>
struct DataType< ::gsdf_msgs::CommHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gsdf_msgs/CommHeader";
  }

  static const char* value(const ::gsdf_msgs::CommHeader_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gsdf_msgs::CommHeader_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 source\n\
int8 type\n\
int16 data_len\n\
int8 version\n\
int16 checksum\n\
";
  }

  static const char* value(const ::gsdf_msgs::CommHeader_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gsdf_msgs::CommHeader_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.source);
      stream.next(m.type);
      stream.next(m.data_len);
      stream.next(m.version);
      stream.next(m.checksum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommHeader_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gsdf_msgs::CommHeader_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gsdf_msgs::CommHeader_<ContainerAllocator>& v)
  {
    s << indent << "source: ";
    Printer<int16_t>::stream(s, indent + "  ", v.source);
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
    s << indent << "data_len: ";
    Printer<int16_t>::stream(s, indent + "  ", v.data_len);
    s << indent << "version: ";
    Printer<int8_t>::stream(s, indent + "  ", v.version);
    s << indent << "checksum: ";
    Printer<int16_t>::stream(s, indent + "  ", v.checksum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GSDF_MSGS_MESSAGE_COMMHEADER_H
