// Generated by gencpp from file gsdf_msgs/NeighborBroadcastKeyValue.msg
// DO NOT EDIT!


#ifndef GSDF_MSGS_MESSAGE_NEIGHBORBROADCASTKEYVALUE_H
#define GSDF_MSGS_MESSAGE_NEIGHBORBROADCASTKEYVALUE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gsdf_msgs
{
template <class ContainerAllocator>
struct NeighborBroadcastKeyValue_
{
  typedef NeighborBroadcastKeyValue_<ContainerAllocator> Type;

  NeighborBroadcastKeyValue_()
    : key()
    , value()  {
    }
  NeighborBroadcastKeyValue_(const ContainerAllocator& _alloc)
    : key(_alloc)
    , value(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _key_type;
  _key_type key;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::gsdf_msgs::NeighborBroadcastKeyValue_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gsdf_msgs::NeighborBroadcastKeyValue_<ContainerAllocator> const> ConstPtr;

}; // struct NeighborBroadcastKeyValue_

typedef ::gsdf_msgs::NeighborBroadcastKeyValue_<std::allocator<void> > NeighborBroadcastKeyValue;

typedef boost::shared_ptr< ::gsdf_msgs::NeighborBroadcastKeyValue > NeighborBroadcastKeyValuePtr;
typedef boost::shared_ptr< ::gsdf_msgs::NeighborBroadcastKeyValue const> NeighborBroadcastKeyValueConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gsdf_msgs::NeighborBroadcastKeyValue_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gsdf_msgs::NeighborBroadcastKeyValue_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gsdf_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'gsdf_msgs': ['/home/plankton/DDP/src/micros_swarm_framework/core/gsdf_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gsdf_msgs::NeighborBroadcastKeyValue_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gsdf_msgs::NeighborBroadcastKeyValue_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gsdf_msgs::NeighborBroadcastKeyValue_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gsdf_msgs::NeighborBroadcastKeyValue_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gsdf_msgs::NeighborBroadcastKeyValue_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gsdf_msgs::NeighborBroadcastKeyValue_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gsdf_msgs::NeighborBroadcastKeyValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1657889729a0518095a6771ffa7222a8";
  }

  static const char* value(const ::gsdf_msgs::NeighborBroadcastKeyValue_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1657889729a05180ULL;
  static const uint64_t static_value2 = 0x95a6771ffa7222a8ULL;
};

template<class ContainerAllocator>
struct DataType< ::gsdf_msgs::NeighborBroadcastKeyValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gsdf_msgs/NeighborBroadcastKeyValue";
  }

  static const char* value(const ::gsdf_msgs::NeighborBroadcastKeyValue_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gsdf_msgs::NeighborBroadcastKeyValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string key\n\
uint8[] value\n\
";
  }

  static const char* value(const ::gsdf_msgs::NeighborBroadcastKeyValue_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gsdf_msgs::NeighborBroadcastKeyValue_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.key);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NeighborBroadcastKeyValue_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gsdf_msgs::NeighborBroadcastKeyValue_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gsdf_msgs::NeighborBroadcastKeyValue_<ContainerAllocator>& v)
  {
    s << indent << "key: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.key);
    s << indent << "value[]" << std::endl;
    for (size_t i = 0; i < v.value.size(); ++i)
    {
      s << indent << "  value[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GSDF_MSGS_MESSAGE_NEIGHBORBROADCASTKEYVALUE_H
