// Generated by gencpp from file gsdf_msgs/SwarmList.msg
// DO NOT EDIT!


#ifndef GSDF_MSGS_MESSAGE_SWARMLIST_H
#define GSDF_MSGS_MESSAGE_SWARMLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gsdf_msgs
{
template <class ContainerAllocator>
struct SwarmList_
{
  typedef SwarmList_<ContainerAllocator> Type;

  SwarmList_()
    : robot_id(0)
    , swarm_list()  {
    }
  SwarmList_(const ContainerAllocator& _alloc)
    : robot_id(0)
    , swarm_list(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _robot_id_type;
  _robot_id_type robot_id;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _swarm_list_type;
  _swarm_list_type swarm_list;





  typedef boost::shared_ptr< ::gsdf_msgs::SwarmList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gsdf_msgs::SwarmList_<ContainerAllocator> const> ConstPtr;

}; // struct SwarmList_

typedef ::gsdf_msgs::SwarmList_<std::allocator<void> > SwarmList;

typedef boost::shared_ptr< ::gsdf_msgs::SwarmList > SwarmListPtr;
typedef boost::shared_ptr< ::gsdf_msgs::SwarmList const> SwarmListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gsdf_msgs::SwarmList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gsdf_msgs::SwarmList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gsdf_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'gsdf_msgs': ['/home/plankton/DDP/src/micros_swarm_framework/core/gsdf_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gsdf_msgs::SwarmList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gsdf_msgs::SwarmList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gsdf_msgs::SwarmList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gsdf_msgs::SwarmList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gsdf_msgs::SwarmList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gsdf_msgs::SwarmList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gsdf_msgs::SwarmList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f621a20b31f30285c93ed9d370693ac7";
  }

  static const char* value(const ::gsdf_msgs::SwarmList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf621a20b31f30285ULL;
  static const uint64_t static_value2 = 0xc93ed9d370693ac7ULL;
};

template<class ContainerAllocator>
struct DataType< ::gsdf_msgs::SwarmList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gsdf_msgs/SwarmList";
  }

  static const char* value(const ::gsdf_msgs::SwarmList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gsdf_msgs::SwarmList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 robot_id\n\
int32[] swarm_list\n\
";
  }

  static const char* value(const ::gsdf_msgs::SwarmList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gsdf_msgs::SwarmList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_id);
      stream.next(m.swarm_list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SwarmList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gsdf_msgs::SwarmList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gsdf_msgs::SwarmList_<ContainerAllocator>& v)
  {
    s << indent << "robot_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot_id);
    s << indent << "swarm_list[]" << std::endl;
    for (size_t i = 0; i < v.swarm_list.size(); ++i)
    {
      s << indent << "  swarm_list[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.swarm_list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GSDF_MSGS_MESSAGE_SWARMLIST_H
